---
- name: Check for existence of config map labeled app={{ app_name }}
  action: command oc get configmap -l app={{ app_name }} -o name --ignore-not-found -n {{ openshift_project_name }}
  register: object_check_result
  
#- debug: var=object_check_result

- name: Create config map json from template
  template:
    src: "jenkins-slave-aqua-config-map.j2"
    dest: "{{ mktemp.stdout }}/jenkins-slave-aqua-config-map.yaml"
  changed_when: no
  when: object_check_result.stdout == ""

- name: Create config map for jenkins-slave-aqua
  action: command bash -c "oc create -f {{ mktemp.stdout }}/jenkins-slave-aqua-config-map.yaml -n {{ openshift_project_name }}"
  when: object_check_result.stdout == ""