---
- name: Include tasks for installing the itweb-jenkins-base image
  include_tasks: install-base-image.yaml
- name: Include tasks for installing the {{ app_name }} application
  include_tasks: install-application.yaml
- name: Start itweb-jenkins-base image build 
  include_tasks: start-build.yaml