apiVersion: v1
kind: Template
metadata:
  name: itweb-nexus3
objects:
# IMAGE STREAM
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: itweb-nexus3
    labels:
      app: itweb-nexus3
  spec:
    lookupPolicy:
      local: false
# BUILD CONFIG 
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: itweb-nexus3
    labels:
      app: itweb-nexus3
  spec:
    strategy:
      dockerStrategy:
      type: Docker
    source:
      type: Dockerfile
      dockerfile: |
        FROM sonatype/nexus3:3.12.1
        USER root
        RUN yum update -y
        USER 1001    
    output:
      to:
        kind: ImageStreamTag
        name: 'itweb-nexus3:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    triggers: {}
# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: itweb-nexus3
    name: itweb-nexus3
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: itweb-nexus3
      deploymentconfig: itweb-nexus3
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: itweb-nexus3
          deploymentconfig: itweb-nexus3
      spec:
        containers:
        - image: itweb-nexus3
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: itweb-nexus3
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /repository/maven-public/
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: itweb-nexus3-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: itweb-nexus3-data
#        - name: itweb-nexus3-data
#          persistentVolumeClaim:
#            claimName: itweb-nexus3
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - itweb-nexus3
        from:
          kind: ImageStreamTag
          name: itweb-nexus3:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
# SERVICE
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: itweb-nexus3
    name: itweb-nexus3
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: itweb-nexus3
      deploymentconfig: itweb-nexus3
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# PERSISTENT VOLUME CLAIM      
#- apiVersion: v1
#  kind: PersistentVolumeClaim
#  metadata:
#    name: itweb-nexus3
#    labels:
#      app: itweb-nexus3
#  spec:
#    accessModes:
#    - ReadWriteOnce
#    resources:
#      requests:
#        storage: 5Gi