apiVersion: v1
kind: Template
metadata:
  name: itweb-zipkin
  labels:
  annotations:
    description: A Template for ITWEB's Zipkin service
    iconClass: icon-spring
    tags: spring-boot, spring-cloud, itweb, development
    openshift.io/display-name: ITWEB - Zipkin
objects:
# IMAGE STREAM
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: itweb-zipkin
    labels:
      app: ${APP_NAME}
# BUILD CONFIG
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}    
  spec:
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'itweb-springboot-runtime:latest'
      type: Docker
    source:
      type: Docker
      dockerfile: |-
        FROM itweb-springboot-runtime
        EXPOSE 9411
        RUN wget -O zipkin.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'
        RUN chown -R 1001:0 zipkin.jar
        USER 1001
        ENTRYPOINT ["java", "-jar", "zipkin.jar"]
    output:
      to:
        kind: ImageStreamTag
        name: itweb-zipkin:latest
    triggers:
    - imageChange: {}
    - type: ConfigChange
# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: 9411
            protocol: TCP
          resources: 
              requests: 
                cpu: 300m
                memory: 1Gi
              limits:
                cpu: 900m
                memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: itweb-zipkin:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
# SERVICE    
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 9411-tcp
      port: 9411
      protocol: TCP
      targetPort: 9411
    selector:
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# ROUTE    
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    host: ${ROUTE_HOST}
    port:
      targetPort: 9411-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
  status: {}
parameters:
- description: The name of the new application
  displayName: Application Name
  name: APP_NAME
  value: zipkin
  required: true
- description: The hostname for the route
  displayName: Route Host
  name: ROUTE_HOST
  value: zipkin.awsos2.americancentury.com
  required: true
- description: Maximum CPU
  displayName: Maximum CPU
  name: MAX_CPU
  value: 500m
  required: true
- description: Maximum Memory
  displayName: Maximum Memory
  name: MAX_MEM
  value: 1Gi
  required: true