apiVersion: v1
kind: Template
metadata:
  name: itweb-zipkin
  labels:
  annotations:
    description: A Template for the zipkin service
    iconClass: icon-spring
    tags: spring-boot, spring-cloud, itweb, development
    openshift.io/display-name: ITWEB - Zipkin
objects:
# IMAGE STREAM
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: itweb-zipkin
    labels:
      app: itweb-zipkin
# BUILD CONFIG
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: itweb-zipkin
    labels:
      app: itweb-zipkin    
  spec:
    strategy:
      type: Docker
    source:
      type: Docker
      dockerfile: |-
        FROM openjdk:8-jre-alpine
        EXPOSE 9411
        RUN wget -O zipkin.jar 'https://search.maven.org/remote_content?g=io.zipkin.java&a=zipkin-server&v=LATEST&c=exec'
        RUN chown -R 1001:0 zipkin.jar
        USER 1001
        ENTRYPOINT ["java", "-jar", "zipkin.jar"]
    output:
      to:
        kind: ImageStreamTag
        name: itweb-zipkin:latest
    triggers:
    - imageChange: {}
    - type: ConfigChange
# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: itweb-zipkin
    name: itweb-zipkin
  spec:
    replicas: 1
    selector:
      app: itweb-zipkin
      deploymentconfig: itweb-zipkin
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: itweb-zipkin
          deploymentconfig: itweb-zipkin
      spec:
        containers:
        - imagePullPolicy: Always
          name: itweb-zipkin
          ports:
          - containerPort: 9411
            protocol: TCP
          resources: 
              requests: 
                cpu: 300m
                memory: 1Gi
              limits:
                cpu: 900m
                memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - itweb-zipkin
        from:
          kind: ImageStreamTag
          name: itweb-zipkin:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
# SERVICE    
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: itweb-zipkin
    name: itweb-zipkin
  spec:
    ports:
    - name: 9411-tcp
      port: 9411
      protocol: TCP
      targetPort: 9411
    selector:
      deploymentconfig: itweb-zipkin
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# ROUTE    
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: itweb-zipkin
    name: itweb-zipkin
  spec:
    host: zipkin.awsos2.americancentury.com
    port:
      targetPort: 9411-tcp
    to:
      kind: Service
      name: itweb-zipkin
      weight: 100
    wildcardPolicy: None
  status: {}