---
openshift_project_name: itweb-ci-cd
git_url: ssh://APKAIYMS5Y3AMAIY4L2A@git-codecommit.us-east-2.amazonaws.com/v1/repos/itweb-jenkins
git_branch: develop
git_secret: git-private-key
volume_capacity: 2Gi
cpu_limit: 1500m
memory_limit: 2Gi
route_host: jenkins.awsos2.americancentury.com