---
openshift_project_name: itweb-development
openshift_project_display_name: 'ITWEB - Development'
openshift_project_description: 'The development namespace for ITWEB applications'
autostart_pipeline: false
openshift_ci_cd_project_name: itweb-ci-cd
openshift_infra_project_name: itweb-infra