---
openshift_project_name: aqua-security
openshift_project_display_name: 'Aqua Security'
openshift_project_description: 'Aqua Container Security'
openshift_project_admin_user: admin
app_name: aqua
aqua_postgres_password: password
aqua_admin_password: aquaTest123
route_host: aqua.awsos2.americancentury.com
