---
- name: Check for existence of a secret named dockerhub
  action: command oc get secret dockerhub -o name --ignore-not-found -n {{ openshift_project_name }}
  register: secret_check_result
  
#- debug: var=secret_check_result

- name: Create secret named dockerhub
  action: command bash -c "oc create secret dockerhub --docker-server=https://index.docker.io/v1/ --docker-username={{ dockerhub_username }} --docker-password={{ dockerhub_password }} --docker-email={{ dockerhub_email }} -n {{ openshift_project_name }}"
  when: secret_check_result.stdout == ""