---
- name: Check for existence of a service account named {{ app_name }}-account
  action: command oc get sa {{ app_name }}-account -o name --ignore-not-found -n {{ openshift_project_name }}
  register: account_check_result
  
#- debug: var=account_check_result

- name: Create service account named {{ app_name }}-account
  action: command bash -c "oc create serviceaccount {{ app_name }}-account -n {{ openshift_project_name }}"
  when: account_check_result.stdout == ""

- name: Add cluster-reader role bindings for {{ app_name }}-account
  action: command bash -c "oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:{{ openshift_project_name }}:{{ app_name }}-account"
  
- name: Set {{ app_name }}-account as privileged
  action: command bash -c "oc adm policy add-scc-to-user privileged system:serviceaccount:{{ openshift_project_name }}:{{ app_name }}-account"