---
- include_vars:
    file: main.yaml

- include_tasks: ../../../shared/tasks/openshift/create-openshift-project.yaml

- include_tasks: create-serviceaccount.yaml
- include_tasks: install-database.yaml