apiVersion: v1
kind: Template
metadata:
  name: configuration-service
  annotations:
    description: Spring Configuration Server
    iconClass: icon-spring
    tags: builder, spring-boot, spring-cloud, config
objects:
# IMAGE STREAM DEFINITION
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
    creationTimestamp: null
  spec: {}
  status:
    dockerImageRepository:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-builder
    labels:
      app: ${APP_NAME}
    creationTimestamp: null
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openjdk
  spec:
    tags:
    - from:
        kind: DockerImage
        name: openjdk:8-jre-alpine
      name: 8-jre-alpine
      referencePolicy:
        type: Source    
# BUILD CONFIG
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}-builder
    labels:
      app: ${APP_NAME}
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
      sourceSecret:
        name: ${GIT_SECRET}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: springboot-s2i:latest
          namespace: dev-poc
        env:
          - name: NEXUS_HOST
            value: http://nexus3.ci-cd.svc:8081
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}-builder:latest
    triggers:
    - type: ConfigChange
    - type: ImageChange 
      imageChange: {}
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_URL}
        ref: ${GIT_REF}
      sourceSecret:
            name: ${GIT_SECRET}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: springboot-s2i:latest
        env:
          - name: NEXUS_HOST
            value: http://nexus3.ci-cd.svc:8081          
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    triggers:
    - generic:
        secret: ${GENERIC_TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: false
          containerNames:
            - ${APP_NAME}
          from:
            kind: ImageStreamTag
            name: '${APP_NAME}:latest'
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
          - env:
            - name: spring_cloud_config_server_git_uri
              value: >-
                ssh://APKAIYMS5Y3AMAIY4L2A@git-codecommit.us-east-2.amazonaws.com/v1/repos/aci-itweb-config
            - name: spring_cloud_config_server_git_privateKey
              valueFrom:
                secretKeyRef:
                  key: ssh-privatekey
                  name: git-private-key
            name: ${APP_NAME}
            image: ${APP_NAME}
            ports:
              - containerPort: 8888
                protocol: TCP
              - containerPort: 8081
                protocol: TCP
            resources: 
              requests: 
                cpu: ${MIN_CPU}
                memory: ${MIN_MEM}
              limits:
                cpu: ${MAX_CPU}
                memory: ${MAX_MEM}
            readinessProbe:
              httpGet:
                path: /health
                port: 8081
                scheme: HTTP
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: /dev/termination-log
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
  status: {}
# SERVICE CONFIG
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
      - name: 8888-tcp
        protocol: TCP
        port: 8888
        targetPort: 8888
      - name: 8081-tcp
        protocol: TCP
        port: 8081
        targetPort: 8081
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
# ROUTE CONFIG
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    host: ${ROUTE_HOST}
    to:
      kind: Service
      name: ${APP_NAME}
    port:
      targetPort: 8888-tcp
    wildcardPolicy: None
parameters:
- description: The name of the new application
  displayName: Application Name
  name: APP_NAME
  value: configuration-service
  required: true
- description: The URL of the Git repository
  displayName: Git URL
  name: GIT_URL
  value: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/aci-itweb-config-service
  required: true
- description: The Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  value: master
  required: true
- description: The secret containing Git credentials
  displayName: Git Credentials Secret
  name: GIT_SECRET
  value: git-secret
  required: true
- description: Generic build Trigger Secret
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: GENERIC_TRIGGER_SECRET
- description: The hostname for the route
  displayName: Route Host
  name: ROUTE_HOST
  value: config.awsos1.americancentury.com
  required: true
- description: Minimum CPU
  displayName: Minimum CPU
  name: MIN_CPU
  value: 300m
  required: true
- description: Minimum Memory
  displayName: Minimum Memory
  name: MIN_MEM
  value: 1Gi
  required: true
- description: Maximum CPU
  displayName: Maximum CPU
  name: MAX_CPU
  value: 900m
  required: true
- description: Maximum Memory
  displayName: Maximum Memory
  name: MAX_MEM
  value: 2Gi
  required: true