apiVersion: v1
kind: Template
metadata:
  name: declarative-pipeline
  annotations:
    description: A test template for declarative pipelines
    iconClass: icon-jenkins
    tags: pipeline, jenkins, git, itweb
objects:
# BUILD CONFIG
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: declarative-pipeline
  spec:
    runPolicy: Serial
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: >
          pipeline {
            agent { node { label 'maven'} }
            stages {
              stage('Stage 1') {
                steps {
                  echo 'Stage 1'
                }
              }
            }
          }
      type: JenkinsPipeline