apiVersion: v1
kind: BuildConfig
metadata:
  name: test-jenkins
spec:
  source:                       
    git:
      uri: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/itweb-jenkins
    type: Git
    sourceSecret:
      name: git-secret    
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: itweb-jenkins:latest