apiVersion: v1
kind: List
items:
# IMAGE STREAM -- itweb-jenkins
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: itweb-jenkins
    name: itweb-jenkins
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations:
          description: The Jenkins image for ITWEB
          tags: itweb-jenkins
# BUILD CONFIG -- itweb-jenkins 
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: itweb-jenkins
    labels:
      app: itweb-jenkins
  spec:
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: 'openshift/jenkins-2-centos7:v3.9'
      type: Source
    source:          
      git:
        uri: https://git-codecommit.us-east-2.amazonaws.com/v1/repos/itweb-jenkins
      type: Git
      sourceSecret:
        name: git-secret    
    output:
      to:
        kind: ImageStreamTag
        name: 'itweb-jenkins:latest'
    postCommit: {}
    resources: {}
    runPolicy: Serial
    triggers:
      - generic:
          secret: itweb-jenkins
        type: Generic
