apiVersion: v1
kind: ImageStream
metadata:
  annotations:
  labels:
    app: itweb-jenkins
  name: itweb-jenkins
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        description: The Jenkins image for ITWEB
        tags: itweb-jenkins