---
- hosts: master_nodes

  pre_tasks:
  - include_tasks: shared/tasks/openshift-login.yaml
  - include_tasks: shared/tasks/pre-install.yaml
      
  roles:
   - admin
   - infrastructure
#  - ci-cd
#  - development
#  - production
                    
  post_tasks:
  - include_tasks: shared/tasks/post-install.yaml