apiVersion: v1
kind: Service
metadata:
  name: aqua-gateway
  labels:
    app: aqua-gateway
spec:
  ports:
    - nodePort: 30036
      port: 3622
      protocol: TCP
      targetPort: 3622
  selector:
    app: aqua-gateway
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aqua-gateway
spec:
  template:
    metadata:
      labels:
        app: aqua-gateway
      name: aqua-gateway
    spec:
      serviceAccount: aqua-account
      #imagePullSecrets:
      #  - name: dockerhub
      containers:
      - name: aqua-gateway
        image: docker-registry.default.svc:5000/aqua-security/aqua-gateway:3.2.rc5
        securityContext:
          privileged: true
        env:
          - name: SCALOCK_GATEWAY_PUBLIC_IP
            value: aqua.awsos.americancentury.com
          - name: SCALOCK_DBUSER
            value: "postgres"
          - name: SCALOCK_DBPASSWORD
            value: "password"
          - name: SCALOCK_DBNAME
            value: "scalock"
          - name: SCALOCK_DBHOST
            value: aqua-db.aqua-security.svc
          - name: SCALOCK_DBPORT
            value: "5432"
          - name: SCALOCK_AUDIT_DBUSER
            value: "postgres"
          - name: SCALOCK_AUDIT_DBPASSWORD
            value: "password"
          - name: SCALOCK_AUDIT_DBNAME
            value: "slk_audit"
          - name: SCALOCK_AUDIT_DBHOST
            value: aqua-db.aqua-security.svc
          - name: SCALOCK_AUDIT_DBPORT
            value: "5432"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-mount
        ports:
        - containerPort: 3622
      volumes:
        - name: docker-socket-mount
          hostPath:
            path: /var/run/docker.sock
