apiVersion: v1
items:
# DEPLOYMENT CONFIG
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: aci-conjur
    name: aci-conjur
  spec:
    replicas: 1
    selector:
      app: aci-conjur
      deploymentconfig: aci-conjur
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        labels:
          app: aci-conjur
          deploymentconfig: aci-conjur
      spec:
        containers:
        - env:
          - name: DATABASE_URL
            value: postgres://userJVU:Hrk6QWtB6i02SAmU@postgresql/sampledb
          - name: CONJUR_DATA_KEY
            value: +lydyIHNekCxTjcHpZr+w7g4Ihu1M2LHUhbddyi0LEU=
          image: docker-registry.default.svc:5000/security-poc/aci-conjur@sha256:15f2c0b853b9fee45686d6f65e2b9c2bc817a9f7410e20b8b71e779fd696a7a1
          imagePullPolicy: Always
          name: aci-conjur
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - aci-conjur
        from:
          kind: ImageStreamTag
          name: aci-conjur:latest
          namespace: security-poc
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: aci-conjur
    name: aci-conjur
  spec:
    ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 80
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: aci-conjur
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}