---
- name: Check for existence of build and image labeled template=itweb-springboot-runtime
  action: command oc get is -l template=itweb-springboot-runtime -o name --ignore-not-found -n {{ openshift_project_name }}
  register: image_check_result
  
#- debug: var=image_check_result

- name: Create itweb-springboot-runtime imagestream and build config json from template
  template:
    src: "springboot-runtime-build.j2"
    dest: "{{ mktemp.stdout }}/springboot-runtime-build.yaml"
  changed_when: no
  when: image_check_result.stdout == ""

- name: Install itweb-springboot-runtime imagestream and build config
  action: command bash -c "oc create -f {{ mktemp.stdout }}/springboot-runtime-build.yaml -n {{ openshift_project_name }}"
  when: image_check_result.stdout == ""

- name: Start the itweb-springboot-runtime build
  action: command bash -c "oc start-build itweb-springboot-runtime -n {{ openshift_project_name }}"
  when: image_check_result.stdout == ""