---
- include_vars:
    file: main.yaml

- include_tasks: shared/tasks/openshift/create-openshift-project.yaml
- include_tasks: shared/tasks/openshift/create-git-private-key.yaml
- include_tasks: create-rolebindings.yaml
- include_tasks: create-springboot-s2i-build.yaml
- include_tasks: create-springboot-runtime-build.yaml
- include_tasks: shared/tasks/openshift/create-bootstrap-config.yaml

- include_role:
    name: configuration-service

- include_role:
    name: auth-n

- name: Create certificate-service application
  include_role:
    name: springboot-application
  vars:
    app_name: certificate-service
    git_url: ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/itweb-mock-certificate-api
    git_ref: develop
    route_host: certificate.awsos2.americancentury.com