---
- include_vars:
    file: main.yaml

- include_tasks: ../../../shared/tasks/openshift/create-openshift-project.yaml
- include_tasks: create-rolebindings.yaml

#- include_role:
#    name: certificate-service
#  vars:
#    route_host: certificate.awsos2.americancentury.com