---
#- name: Add system:image-puller role to system:serviceaccounts:{{ openshift_project_name }}
#  action: command oc adm policy add-role-to-group system:image-puller system:serviceaccounts:{{ openshift_project_name }} --role-namespace=infrastructure --rolebinding-name=infrastructure:image-pullers -n infrastructure
  
- name: Add edit role to system:serviceaccount:{{openshift_ci_cd_project_name }} in {{ openshift_project_name }}
  action: command oc policy add-role-to-user edit system:serviceaccount:{{ openshift_ci_cd_project_name }}:jenkins -n {{ openshift_project_name }}  