---
- set_fact:
    image_stream_name: {{ app_name }}
- include_tasks: ../../../shared/tasks/openshift/create-image_stream.yaml

- set_fact:
    image_stream_name: "{{ app_name }}-builder"
- include_tasks: ../../../shared/tasks/openshift/create-image_stream.yaml

#- include_tasks: install-application.yaml
#- include_tasks: install-pipeline.yaml
#- include_tasks: start-pipeline.yaml